# .github/docker-image-matrix.yml
matrix:
  - name: alpine
    version: latest
    context: "openrc/alpine"
    path: "openrc/alpine"
    platforms: "linux/amd64"
    systemd-distro:
      tags: |-
        lj020326/openrc-alpine:latest
    systemd-python-distro:
      tags: |-
        lj020326/openrc-alpine-python:latest

  - name: aports-dev
    version: latest
    context: "aports-dev"
    path: "aports-dev"
    platforms: "linux/amd64"
    systemd-distro:
      tags: |-
        lj020326/aports-dev:edge
    systemd-python-distro:
      tags: |-
        lj020326/aports-dev-python:edge

  - name: centos9
    version: 9
    context: "systemd/centos"
    path: "systemd/centos"
    platforms: "linux/amd64"
    systemd-distro:
      tags: |-
        lj020326/systemd-centos:9
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-centos:9

  - name: centos10
    version: "10"
    context: "systemd/centos"
    path: "systemd/centos"
    platforms: "linux/amd64"
    systemd-distro:
      tags: |-
        lj020326/systemd-centos:10
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-centos:10

  - name: debian11
    version: 11
    context: "systemd/debian"
    path: "systemd/debian"
    platforms: "linux/amd64,linux/arm64"
    systemd-distro:
      tags: |-
        lj020326/systemd-debian:11
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-debian:11

  - name: debian12
    version: 12
    context: "systemd/debian"
    path: "systemd/debian"
    platforms: "linux/amd64,linux/arm64"
    systemd-distro:
      tags: |-
        lj020326/systemd-debian:12
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-debian:12

  - name: fedora
    version: latest
    context: "systemd/fedora"
    path: "systemd/fedora"
    platforms: "linux/amd64"
    systemd-distro:
      tags: |-
        lj020326/systemd-fedora:latest
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-fedora:latest

  - name: redhat8
    version: 8
    context: "systemd/redhat"
    path: "systemd/redhat"
    platforms: "linux/amd64"
    systemd-distro:
      tags: |-
        lj020326/systemd-redhat:8
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-redhat:8

  - name: ubuntu22
    version: 22.04
    context: "systemd/ubuntu"
    path: "systemd/ubuntu"
    platforms: "linux/amd64,linux/arm64"
    systemd-distro:
      tags: |-
        lj020326/systemd-ubuntu:22.04
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-ubuntu:22.04

  - name: ubuntu24
    version: 24.04
    context: "systemd/ubuntu"
    path: "systemd/ubuntu"
    platforms: "linux/amd64,linux/arm64"
    systemd-distro:
      tags: |-
        lj020326/systemd-ubuntu:24.04
    systemd-python-distro:
      tags: |-
        lj020326/systemd-python-ubuntu:24.04
