name: Docker redhat images build

on:
  ## ref: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
    branches: ['*']
  # Schedule updates (once daily)
  schedule:
    ## Daily Docker Image Rebuild (3:29pm daily)
    - cron: '29 15 * * *'

## ref: https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
concurrency:
#  group: ${{ github.ref }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-systemd-redhat:
    runs-on: ubuntu-latest

#    ## ref: https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
#    concurrency:
#      group: ${{ github.workflow }}-${{ github.ref }}
#      cancel-in-progress: true
##      group: ${{ github.workflow }}-systemd-redhat-${{ github.ref }}
###      cancel-in-progress: true

    strategy:
      fail-fast: false
      ## ref: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
#      max-parallel: 2
      matrix:
        include:
#          - distro: redhat7
#            systemd-distro:
#              name: systemd-redhat7
#              dockerfile: systemd/redhat/7.Dockerfile
#              context: systemd/redhat
#              platforms: |-
#                linux/amd64
#              tags: |-
#                lj020326/redhat7-systemd:latest
#            systemd-python-distro:
#              name: systemd-redhat7-python
#              dockerfile: systemd/redhat/7.python.Dockerfile
#              context: systemd/redhat
#              platforms: |-
#                linux/amd64
#              tags: |-
#                lj020326/redhat7-systemd-python:latest

          - distro: redhat8
            systemd-distro:
              name: systemd-redhat8
              dockerfile: systemd/redhat/8.Dockerfile
              context: systemd/redhat
              platforms: |-
                linux/amd64
                linux/arm64
              tags: |-
                lj020326/redhat8-systemd:latest
            systemd-python-distro:
              name: systemd-redhat8-python
              dockerfile: systemd/redhat/8.python.Dockerfile
              context: systemd/redhat
              platforms: |-
                linux/amd64
                linux/arm64
              tags: |-
                lj020326/redhat8-systemd-python:latest

          - distro: redhat9
            systemd-distro:
              name: systemd-redhat9
              dockerfile: systemd/redhat/9.Dockerfile
              context: systemd/redhat
              platforms: |-
                linux/amd64
                linux/arm64
              tags: |-
                lj020326/redhat9-systemd:latest
            systemd-python-distro:
              name: systemd-redhat9-python
              dockerfile: systemd/redhat/9.python.Dockerfile
              context: systemd/redhat
              platforms: |-
                linux/amd64
                linux/arm64
              tags: |-
                lj020326/redhat9-systemd-python:latest
          - distro: redhat10
            systemd-distro:
              name: systemd-redhat10
              dockerfile: systemd/redhat/10.Dockerfile
              context: systemd/redhat
              platforms: |-
                linux/amd64
                linux/arm64
              tags: |-
                lj020326/redhat10-systemd:latest
#            systemd-python-distro:
#              name: systemd-redhat10-python
#              dockerfile: systemd/redhat/10.python.Dockerfile
#              context: systemd/redhat
#              platforms: |-
#                linux/amd64
#                linux/arm64
#              tags: |-
#                lj020326/redhat10-systemd-python:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: If the same workflow is already running from a previous commit, wait for it to finish
        uses: ahmadnassri/action-workflow-queue@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      ## ref: https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: lj020326
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.systemd-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.systemd-distro.context }}
          file: ${{ matrix.systemd-distro.dockerfile }}
          platforms: ${{ matrix.systemd-distro.platforms }}
          build-args: |
            BUILD_ID=${{ steps.date.outputs.date }}.${{ github.run_number }}
          push: true
          tags: ${{ matrix.systemd-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push ${{ matrix.systemd-python-distro.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.systemd-python-distro.context }}
          file: ${{ matrix.systemd-python-distro.dockerfile }}
          platforms: ${{ matrix.systemd-python-distro.platforms }}
          build-args: |
            IMAGE_REGISTRY=${{ github.repository_owner }}
            BUILD_ID=${{ steps.date.outputs.date }}.${{ github.run_number }}
          push: true
          tags: ${{ matrix.systemd-python-distro.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
